version: '2'
services:
  firefox:
    image: acefei/node-firefox
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  chrome:
    image: acefei/node-chrome
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      HUB_HOST: hub

  phantomjs:
    image: acefei/node-phantomjs
    depends_on:
      - hub

  hub:
    image: selenium/hub
    ports:
      - "4444:4444"
